spring:
  datasource: 
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/battery_plus
    username: postgres
    password: sql
    hikari:
      poolName: SpringBootJPAHikariCP
      connectionTimeout: 30000
      maxLifetime: 2000000
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
  jpa:
    hibernate:
      connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql: true
        search.autoregister_listeners: false
        bytecode:
          use_reflection_optimizer: false
        temp:
          use_jdbc_metadata_defaults: false

        





#spring.datasource.type=com.zaxxer.hikari.HikariDataSource
#spring.datasource.hikari.minimumIdle=5
#spring.datasource.hikari.maximumPoolSize=20
#spring.datasource.hikari.idleTimeout=30000
#spring.datasource.hikari.poolName=SpringBootJPAHikariCP
#spring.datasource.hikari.maxLifetime=2000000
#spring.datasource.hikari.connectionTimeout=30000
#spring.datasource.url=jdbc:postgresql://localhost:5432/batteryplus
#spring.datasource.username=postgres
#spring.datasource.password=sql


#spring.jpa.hibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql=true
#spring.jpa.properties.hibernate.search.autoregister_listeners=false
#spring.jpa.properties.hibernate.bytecode.use_reflection_optimizer=false
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#grokonez.app.jwtSecret=jwtGrokonezSecretKey
#grokonez.app.jwtExpiration=86400
